Масюков, ЛР2 (Hash) - 7 вариант
tapoton/PLT_2017_2sem_2c_4gr pull request #10
Opened 2017-03-18 21:08 UTC by rrrazor

ЛР2 (Hash) - 7 вариант и ЛР1 поправил

2017-03-18 21:28 UTC, rrrazor commented
Теперь ввод оканчивается вводом точки
Пример ввода внизу файла

2017-03-20 07:27 UTC, tapoton requested changes
Вынести информацию о машине в отдельную структуру данных

2017-03-20 07:28 UTC, tapoton commented
Следующее задание
12.   По системе двусторонних дорог, определить можно ли закрыв какие-либо 3 из них, добиться того, чтобы из города А нельзя было попасть в город Б.

2017-03-27 05:13 UTC, tapoton approved these changes

2017-03-27 05:13 UTC, merged