Longest word in Trie Tree Gotsev lab 1
tapoton/PLT_2017_2sem_2c_4gr pull request #27
Opened 2017-04-03 06:24 UTC by Pavel36

2017-04-03 07:29 UTC, tapoton requested changes
Добавил в дерево слово austroneerqwer, самым длинным осталось слово austroneer

2017-04-08 17:55 UTC, Pavel36 commented
исправил ошибку

2017-04-09 12:17 UTC, tapoton approved these changes

2017-04-09 12:17 UTC, merged

2017-04-10 07:52 UTC, tapoton commented
Задан набор записей следующей структуры: табельный номер, ФИО, заработная плата. По табельному номеру найти остальные сведения.