lab 4
tapoton/PLT_2017_2sem_2c_4gr pull request #83
Opened 2017-06-07 09:28 UTC by CellarD0-0r

Поиск кратчайшего пути коня на шахматной доске

2017-06-08 07:01 UTC, tapoton requested changes
Задача на графы. Графа не вижу: в графах нет понятия "может пойти/не может пойти". Есть ребро или нет ребра. Эта информация задается при создании графа.
Каждая клетка, вершина графа, соединена ребром только с теми клетками, куда может пойти конь.

2017-06-09 08:46 UTC, CellarD0-0r commented
@tapoton 
В данном случае подразумевается, что "может/не может пойти" обозначает именно наличие либо отсутствие ребра. Отличие только в том, что матрица смежности не хранится в памяти целиком, а как бы генерируется участками по мере поиска пути.

2017-06-09 08:54 UTC, tapoton commented on Borushko/lab4/Source.cpp
> +				Q.pop();
Кстати, можно ли заменить
```c++
int x = Q.front();
Q.pop();

```
на
```c++
int x = Q.pop();
```
?

2017-06-09 08:55 UTC, tapoton commented
А какой алгоритм на графах вы используете?

2017-06-09 09:10 UTC, CellarD0-0r commented
@tapoton 
1. Заменить нельзя, в стандартной библиотеке Q.pop() имеет тип void.
2. Алгоритм, похожий на А*, который ищет кратчайший путь по первому наилучшему совпадению. Строится матрица достижимости из заданной точки во все остальные.

2017-06-09 13:39 UTC, merged